Numpy

In [4]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [ ]:
arr3=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
array = np.array([[2,4,6],[1,3,9]])

print(array)
print(array.size)
print(array.ndim)
print(array.shape)
print(array.dtype)
print(array.itemsize)

[[2 4 6]
 [1 3 9]]
6
2
(2, 3)
int32
4


In [19]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(np.sqrt(arr1))
print(np.sin(arr2))
print(np.log(arr2))

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
[1.         1.41421356 1.73205081 2.         2.23606798]
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


In [30]:
array1 = np.array([[1,2,3,4,5],[10,20,30,40,50]])
array1[0][0]
array1[0:]

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

Pandas


In [32]:
import pandas as pd
data = [1,2,3,4,5]
series=pd.Series(data)
print(series)
print(type(series))


0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>


In [34]:
data2 = {'a':1,'b':2,'c':3}
series_dict = pd.Series(data2)
print(series_dict)

a    1
b    2
c    3
dtype: int64


In [35]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data,index)

a    10
b    20
c    30
dtype: int64

DataFrame

In [38]:
dict = {
    'Name' : ['John' , 'Chungus' , 'James'],
    'Age'  : [20,29,30], 
    'City' :['asr' , 'dlh' , 'Blr']
}

df = pd.DataFrame(dict)
print(df)
print(type(df))

      Name  Age City
0     John   20  asr
1  Chungus   29  dlh
2    James   30  Blr
<class 'pandas.DataFrame'>


In [40]:
data = [
    {'Name' : 'John' , 'Age' : 20 , 'Job' : 'Analyst'},
    {'Name' : 'Jack' , 'Age' : 31 , 'Job' : 'Web Dev'},
    {'Name' : 'Jill' , 'Age' : 21 , 'Job' : 'Ml engineer'},
] 

df = pd.DataFrame(data)
print(df)

   Name  Age          Job
0  John   20      Analyst
1  Jack   31      Web Dev
2  Jill   21  Ml engineer


In [41]:
df = pd.read_csv('vgsales.csv')
df.head(5)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37


In [42]:
df.tail(5)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.0,0.0,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.0,0.0,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.0,0.0,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.0,0.0,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.0,0.0,0.01


In [43]:
data

[{'Name': 'John', 'Age': 20, 'Job': 'Analyst'},
 {'Name': 'Jack', 'Age': 31, 'Job': 'Web Dev'},
 {'Name': 'Jill', 'Age': 21, 'Job': 'Ml engineer'}]

In [5]:
import pandas as pd
data = [
    {'Name' : 'John' , 'Age' : 20 , 'Job' : 'Analyst'},
    {'Name' : 'Jack' , 'Age' : 31 , 'Job' : 'Web Dev'},
    {'Name' : 'Jill' , 'Age' : 21 , 'Job' : 'Ml engineer'},
] 

df = pd.DataFrame(data)
print(df)

   Name  Age          Job
0  John   20      Analyst
1  Jack   31      Web Dev
2  Jill   21  Ml engineer


In [10]:
df['Salary'] = [50000,60000,70000]
df

,Name,Age,Job,Salary
0,John,20,Analyst,50000
1,Jack,31,Web Dev,60000
2,Jill,21,Ml engineer,70000


In [ ]:
df.drop('Salary',axis=1) ##temporary 

,Name,Age,Job
0,John,20,Analyst
1,Jack,31,Web Dev
2,Jill,21,Ml engineer


In [13]:
df['Age'] = df['Age'] + 1

In [14]:
df

,Name,Age,Job,Salary
0,John,21,Analyst,50000
1,Jack,32,Web Dev,60000
2,Jill,22,Ml engineer,70000


In [15]:
print("Data Types :\n", df.dtypes)

print("Statistical summary: \n", df.describe())



Data Types :
 Name        str
Age       int64
Job         str
Salary    int64
dtype: object
Statistical summary: 
              Age   Salary
count   3.000000      3.0
mean   25.000000  60000.0
std     6.082763  10000.0
min    21.000000  50000.0
25%    21.500000  55000.0
50%    22.000000  60000.0
75%    27.000000  65000.0
max    32.000000  70000.0


In [16]:
df = pd.read_csv('data.csv')

In [17]:
df

,Date,Category,Value,Product,Sales,Region
0,2023-01-01,A,28.0,Product1,754.0,East
1,2023-01-02,B,39.0,Product3,110.0,North
2,2023-01-03,C,32.0,Product2,398.0,East
3,2023-01-04,B,8.0,Product1,522.0,East
4,2023-01-05,B,26.0,Product3,869.0,North
5,2023-01-06,B,54.0,Product3,192.0,West
6,2023-01-07,A,16.0,Product1,936.0,East
7,2023-01-08,C,89.0,Product1,488.0,West
8,2023-01-09,C,37.0,Product3,772.0,West
9,2023-01-10,A,22.0,Product2,834.0,West


In [18]:
df.head(5)

,Date,Category,Value,Product,Sales,Region
0,2023-01-01,A,28.0,Product1,754.0,East
1,2023-01-02,B,39.0,Product3,110.0,North
2,2023-01-03,C,32.0,Product2,398.0,East
3,2023-01-04,B,8.0,Product1,522.0,East
4,2023-01-05,B,26.0,Product3,869.0,North


In [19]:
df.describe()

,Value,Sales
count,47.000000,46.000000
mean,51.744681,557.130435
std,29.050532,274.598584
min,2.000000,108.000000
25%,27.500000,339.000000
50%,54.000000,591.500000
75%,70.000000,767.500000
max,99.000000,992.000000


In [20]:
df.isnull()

,Date,Category,Value,Product,Sales,Region
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False


In [23]:
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15     True
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
32    False
33     True
34    False
35     True
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [24]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [27]:
### filling missing values with the mean of the column

df['Sales_FillNA'] = df['Sales'].fillna(df['Sales'].mean())
df

,Date,Category,Value,Product,Sales,Region,Sales_FillNA
0,2023-01-01,A,28.0,Product1,754.0,East,754.000000
1,2023-01-02,B,39.0,Product3,110.0,North,110.000000
2,2023-01-03,C,32.0,Product2,398.0,East,398.000000
3,2023-01-04,B,8.0,Product1,522.0,East,522.000000
4,2023-01-05,B,26.0,Product3,869.0,North,869.000000
5,2023-01-06,B,54.0,Product3,192.0,West,192.000000
6,2023-01-07,A,16.0,Product1,936.0,East,936.000000
7,2023-01-08,C,89.0,Product1,488.0,West,488.000000
8,2023-01-09,C,37.0,Product3,772.0,West,772.000000
9,2023-01-10,A,22.0,Product2,834.0,West,834.000000


In [28]:
df.any()

Date            True
Category        True
Value           True
Product         True
Sales           True
Region          True
Sales_FillNA    True
dtype: bool

In [32]:
## Renaming columns

df = df.rename(columns={'Date' : 'Sale Date'})
df.head(5)

,Sale Date,Category,Value,Product,Sales,Region,Sales_FillNA
0,2023-01-01,A,28.0,Product1,754.0,East,754.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0


In [34]:
### Changing the datatypes 
df['Value_new'] = df['Value'].fillna(df['Value'].mean()).astype(int)
df.head(5)

,Sale Date,Category,Value,Product,Sales,Region,Sales_FillNA,Value_new
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26


In [35]:
df['New Value'] = df['Value'].apply(lambda x:x*2)
df.head()

,Sale Date,Category,Value,Product,Sales,Region,Sales_FillNA,Value_new,New Value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26,52.0


In [3]:
##data aggregating and grouping 

import pandas as pd

df = pd.read_csv('data.csv')
df.head()

,Date,Category,Value,Product,Sales,Region
0,2023-01-01,A,28.0,Product1,754.0,East
1,2023-01-02,B,39.0,Product3,110.0,North
2,2023-01-03,C,32.0,Product2,398.0,East
3,2023-01-04,B,8.0,Product1,522.0,East
4,2023-01-05,B,26.0,Product3,869.0,North


In [4]:
grouped_mean = df.groupby('Product')['Value'].mean()
print(grouped_mean)

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64


In [5]:
grouped_sum = df.groupby(['Product','Region'])['Value'].sum()
print(grouped_sum)

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64


In [ ]:
## aggregate multiple functions
grouped_agg = df.groupby('Region')['Value'].agg(['mean','sum','count'])
print(grouped_agg)

             mean     sum  count
Region                          
East    42.307692   550.0     13
North   37.666667   339.0      9
South   62.000000   496.0      8
West    61.588235  1047.0     17


In [7]:
### merging and joining dataframes

df1 = pd.DataFrame({'Key' : ['A','B','C'] , 'Value1' : [1,2,3]})
df2 = pd.DataFrame({'Key' : ['A','B','D'] , 'Value2' : [4,5,6]})

In [9]:
df1


,Key,Value1
0,A,1
1,B,2
2,C,3


In [10]:
df2

,Key,Value2
0,A,4
1,B,5
2,D,6


In [11]:
## Merge Dataframe

pd.merge(df1,df2,on="Key",how="inner")

,Key,Value1,Value2
0,A,1,4
1,B,2,5


In [13]:
df_merged = pd.merge(df1,df2,on="Key",how="outer")
print(df_merged)

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0


In [22]:
pd.merge(df1,df2,on="Key",how="left")

,Key,Value1,Value2
0,A,1,4.0
1,B,2,5.0
2,C,3,NaN


In [28]:
## Data Reading
import pandas as pd
from io import StringIO

Data = '{"employee_name" : "James" , "email" : "james@gmail.com" , "job_profile": [{"title1" : "Team Lead", "title2" : "Software Developer"}]}'
df = pd.read_json(StringIO(Data))

In [29]:
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Software De..."


In [30]:
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Software Developer"}}}'

In [31]:
df.to_json(orient='index')

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Software Developer"}}}'

In [32]:
df.to_csv("simple.csv")

In [36]:
url = "https://www.fdic.gov/bank-failures/failed-bank-list"
df = pd.read_html(url)

In [38]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
1,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
2,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
3,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
4,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
5,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
6,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
7,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
8,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
9,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540


In [39]:
df = pd.read_excel('Project-Management-Sample-Data.xlsx')

In [41]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Excel Sample Data,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Project Management Data,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Project Name,Task Name,Assigned to,Start Date,Days Required,End Date,Progress
5,NaN,Marketing,Market Research,Alice,2024-01-01 00:00:00,13,2024-01-14 00:00:00,0.78
6,NaN,Marketing,Content Creation,Bob,2024-01-14 00:00:00,14,2024-01-28 00:00:00,1
7,NaN,Marketing,Social Media Planning,Charlie,2024-01-28 00:00:00,22,2024-02-19 00:00:00,0.45
8,NaN,Marketing,Campaign Analysis,Daisy,2024-02-18 00:00:00,25,2024-03-14 00:00:00,0
9,NaN,Product Dev,Prototype Development,Ethan,2024-01-02 00:00:00,18,2024-01-20 00:00:00,1


In [42]:
df.to_pickle('df_excel')

In [43]:
pd.read_pickle('df_excel')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Excel Sample Data,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Project Management Data,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Project Name,Task Name,Assigned to,Start Date,Days Required,End Date,Progress
5,NaN,Marketing,Market Research,Alice,2024-01-01 00:00:00,13,2024-01-14 00:00:00,0.78
6,NaN,Marketing,Content Creation,Bob,2024-01-14 00:00:00,14,2024-01-28 00:00:00,1
7,NaN,Marketing,Social Media Planning,Charlie,2024-01-28 00:00:00,22,2024-02-19 00:00:00,0.45
8,NaN,Marketing,Campaign Analysis,Daisy,2024-02-18 00:00:00,25,2024-03-14 00:00:00,0
9,NaN,Product Dev,Prototype Development,Ethan,2024-01-02 00:00:00,18,2024-01-20 00:00:00,1
