# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [3]:
import numpy as np 

arr = np.random.randint(1,20,size=(5,5))
print("Original Array : \n",arr)

arr[:,2] = 1
print("Modified Array : \n",arr)
 

Original Array : 
 [[18 15  6  3 19]
 [13  8 13 14  5]
 [ 1 19 16 18  7]
 [14 14 11 17  5]
 [19  6  9 15 19]]
Modified Array : 
 [[18 15  1  3 19]
 [13  8  1 14  5]
 [ 1 19  1 18  7]
 [14 14  1 17  5]
 [19  6  1 15 19]]


In [7]:
arr = np.arange(1,17).reshape(4,4)
print("Original Array : \n", arr)

np.fill_diagonal(arr,0)
print("Modified Array : \n", arr)

Original Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified Array : 
 [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [4]:
arr1 = np.random.randint(1,36,size=[6,6])
subarr = arr1[2:5,1:4]
print("Original Array :\n ",arr1)
print("Modified Array :\n ",subarr)

Original Array :
  [[35 16 14 17  8  5]
 [35 12 30 34  1 14]
 [32 35  9 26 23 25]
 [24 11 34 23 32  6]
 [31 23 22 13 10  8]
 [ 1 17 27 29 23  2]]
Modified Array :
  [[35  9 26]
 [11 34 23]
 [23 22 13]]


In [26]:
arr1 = np.random.randint(1,21,size=(5,5))
print(arr1,"\n")

border_elements = np.concatenate((arr1[0, :], arr1[:, -1], arr1[1: -1, 0], arr1[-1]))
print(border_elements)

[[14  4 19  1 20]
 [11  2 16 12 14]
 [ 9  7  1  8  6]
 [17 11  2 15 15]
 [19 12 20 11  8]] 

[14  4 19  1 20 20 14  6 15  8 11  9 17 19 12 20 11  8]


In [29]:
arr1 = np.random.randint(1,21,size=(3,4))
arr2 = np.random.randint(1,21,size=(3,4))

sum_arr = arr1 + arr2
sub_arr = arr1 - arr2
div_arr = arr1/arr2
mult_arr = arr1*arr2

print(sum_arr)
print(sub_arr)
print(div_arr)
print(mult_arr)


[[33 22 20 24]
 [11 20 13 19]
 [29  8 21 22]]
[[  5 -18  -2 -10]
 [ -5   2  -9  -1]
 [-11  -2   9  -6]]
[[1.35714286 0.1        0.81818182 0.41176471]
 [0.375      1.22222222 0.18181818 0.9       ]
 [0.45       0.6        2.5        0.57142857]]
[[266  40  99 119]
 [ 24  99  22  90]
 [180  15  90 112]]


In [30]:
arr1 = np.random.randint(1,16,size=(4,4))
print("Original Array : \n" , arr1)

row_sum = np.sum(arr1, axis=0)
col_sum = np.sum(arr1, axis=1)

print(row_sum)
print(col_sum)

Original Array : 
 [[12  5  3 13]
 [10 15  5 13]
 [ 7  1  3 11]
 [ 9  4 10  6]]
[38 25 21 43]
[33 43 22 29]


In [2]:
import numpy as np

arr1 = np.random.randint(1,21,size=(5,5))
print("Original Array :", arr1)

arr_mean = np.mean(arr1)
arr_median = np.median(arr1)
arr_std = np.std(arr1)
arr_var = np.var(arr1)

print(arr_mean)
print(arr_median)
print(arr_std)
print(arr_var)


Original Array : [[ 5  5 19  2 15]
 [19 16  5  4 14]
 [16 13 16  3 14]
 [16 15  6  5  3]
 [12 14 16 13  5]]
10.84
13.0
5.597713819051489
31.334400000000002


In [ ]:
arr1 = np.random.randint(1,9,size=(4,4))
print("Original Array : \n",arr1)

mean = np.mean(arr1)
std = np.std(arr1)

normalised_arr = (arr1 - mean) / std

print(normalised_arr)

Original Array : 
 [[3 5 3 1]
 [3 2 1 2]
 [2 1 5 1]
 [8 1 7 1]]
0.6991381018088485


In [5]:
arr1 = np.random.randint(1,11,size=(3,3))
arr2 = np.random.randint(1,11,size=(3,))

print("2-D Array: \n",arr1)
print("1-D Array: \n",arr2)

sum_arr = arr1 + arr2 
print("Result : \n",sum_arr)

2-D Array: 
 [[ 6 10  2]
 [ 3 10  3]
 [ 9  2  2]]
1-D Array: 
 [2 1 3]
Result : 
 [[ 8 11  5]
 [ 5 11  6]
 [11  3  5]]


In [13]:
arr1 = np.random.randint(1,11,size=(4,4))
arr2 = np.random.randint(1,11,size=(4,))

print("2-D Array: \n",arr1)
print("Column Array: \n",arr2)
print(arr2[:,np.newaxis])
sub_arr = arr1 - arr2
print("Result : \n", sub_arr)

np_arr = arr1-arr2[:,np.newaxis]
print("\n",np_arr)


2-D Array: 
 [[10  6 10  1]
 [ 2  3  7  5]
 [10  5  7  4]
 [ 3  6  2  9]]
Column Array: 
 [5 8 8 3]
[[5]
 [8]
 [8]
 [3]]
Result : 
 [[ 5 -2  2 -2]
 [-3 -5 -1  2]
 [ 5 -3 -1  1]
 [-2 -2 -6  6]]

 [[ 5  1  5 -4]
 [-6 -5 -1 -3]
 [ 2 -3 -1 -4]
 [ 0  3 -1  6]]


In [14]:
matrix = np.random.randint(1,11,size=(3,3))
print("Original Matrix : \n", matrix)

det = np.linalg.det(matrix)
inverse = np.linalg.inv(matrix)
equilv = np.linalg.eigvals(matrix)

print(det)
print(inverse)
print(equilv)

Original Matrix : 
 [[ 7 10 10]
 [10  8  9]
 [ 6  6  8]]
-70.00000000000009
[[-0.14285714  0.28571429 -0.14285714]
 [ 0.37142857  0.05714286 -0.52857143]
 [-0.17142857 -0.25714286  0.62857143]]
[24.43775792 -2.55768479  1.11992686]


In [15]:
multiplication  = np.dot(arr1,arr2)
print("Multiplication of two arrays : ",multiplication)

Multiplication of two arrays :  [181 105 158 106]


In [5]:
from matplotlib.pyplot import prism
import numpy as np

array = np.random.randint(1,21,size = (5,5))

flat_arr = array.flatten()
print("Original Array : \n", array)
print("Flattened Array : \n", flat_arr)
print("Reshaped Array : \n",flat_arr.reshape((5,5)))

Original Array : 
 [[ 8 20  4  8  5]
 [ 8  4 20 15  4]
 [12 20  3 14 15]
 [16 17 11 19 12]
 [10 17 11 14 16]]
Flattened Array : 
 [ 8 20  4  8  5  8  4 20 15  4 12 20  3 14 15 16 17 11 19 12 10 17 11 14
 16]
Reshaped Array : 
 [[ 8 20  4  8  5]
 [ 8  4 20 15  4]
 [12 20  3 14 15]
 [16 17 11 19 12]
 [10 17 11 14 16]]


In [9]:
array = np.random.randint(1,21,size = (5,5))
print(array)

corners = array[[0,0,-1,-1],[0,-1,0,-1]]
print(corners)

array[array>10] = 10
print(array)

[[20 10  8  1 13]
 [ 1  3  2  3  2]
 [10 10  7  5 18]
 [15 14 13 17 16]
 [18 12 10 12  6]]
[20 13 18  6]
[[10 10  8  1 10]
 [ 1  3  2  3  2]
 [10 10  7  5 10]
 [10 10 10 10 10]
 [10 10 10 10  6]]


In [10]:
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]
